version: "2"
services:
  wordpress:
    build: .
    image: wordpress:5.9.2-php7.2
    restart: always
    ports:
      - 8001:80
    links:
      - mysql
    volumes:
      - ./:/var/www/html/wp-content/plugins/moovly
    environment:
      VIRTUAL_HOST: wordpressplugin.moovly.docker
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: moovly
      WORDPRESS_DB_USER: moovly
      WORDPRESS_DB_PASSWORD: moovly
      WORDPRESS_CONFIG_EXTRA: define('WP_DEBUG', true);define('WP_DEBUG_DISPLAY', true);

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 33360:3306
    environment:
      MYSQL_DATABASE: moovly
      MYSQL_USER: moovly
      MYSQL_PASSWORD: moovly
      MYSQL_RANDOM_ROOT_PASSWORD: 1
